#!/bin/bash

# MusicMu Cleanup Script
# Removes old dependencies and temporary files

set -e

echo "🧹 MusicMu Cleanup Script"
echo "=========================="
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Navigate to project root
cd "$(dirname "$0")"

echo -e "${BLUE}📦 Checking for old dependencies...${NC}"

# Check if old deps are still installed
if grep -q "@distube/ytdl-core" server/package.json 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Old dependency found: @distube/ytdl-core${NC}"
    echo "Run: cd server && npm uninstall @distube/ytdl-core"
fi

if grep -q "play-dl" server/package.json 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Old dependency found: play-dl${NC}"
    echo "Run: cd server && npm uninstall play-dl"
fi

if grep -q '"axios"' server/package.json 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Old dependency found: axios${NC}"
    echo "Run: cd server && npm uninstall axios"
fi

# Clean old player scripts (generated by youtubei.js)
echo -e "${BLUE}🗑️  Cleaning old player scripts...${NC}"

CLEANED=0
for file in *-player-script.js; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "  Removed: $file"
        ((CLEANED++))
    fi
done

for file in server/*-player-script.js; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "  Removed: $file"
        ((CLEANED++))
    fi
done

if [ $CLEANED -eq 0 ]; then
    echo "  ✅ No player scripts found"
else
    echo -e "  ${GREEN}✅ Cleaned $CLEANED player script(s)${NC}"
fi

# Check node_modules size
echo ""
echo -e "${BLUE}📊 Checking bundle sizes...${NC}"

if [ -d "server/node_modules" ]; then
    SIZE=$(du -sh server/node_modules | cut -f1)
    echo "  Server node_modules: $SIZE"
fi

if [ -d "client/node_modules" ]; then
    SIZE=$(du -sh client/node_modules | cut -f1)
    echo "  Client node_modules: $SIZE"
fi

# Check for build artifacts
echo ""
echo -e "${BLUE}🏗️  Checking build artifacts...${NC}"

if [ -d "server/dist" ]; then
    SIZE=$(du -sh server/dist | cut -f1)
    echo "  ✅ Server build: $SIZE"
else
    echo -e "  ${YELLOW}⚠️  Server not built yet${NC}"
fi

if [ -d "client/dist" ]; then
    SIZE=$(du -sh client/dist | cut -f1)
    echo "  ✅ Client build: $SIZE"
else
    echo -e "  ${YELLOW}⚠️  Client not built yet${NC}"
fi

# Check service status
echo ""
echo -e "${BLUE}🔧 Checking service status...${NC}"

if systemctl is-active --quiet musicmu; then
    echo -e "  ${GREEN}✅ MusicMu service is running${NC}"
else
    echo -e "  ${YELLOW}⚠️  MusicMu service is not running${NC}"
    echo "  Run: sudo systemctl start musicmu"
fi

echo ""
echo -e "${GREEN}✅ Cleanup complete!${NC}"
echo ""
echo "To rebuild and restart:"
echo "  cd server && npm run build"
echo "  sudo systemctl restart musicmu"
